module.exports = {
  FETCHED_PUBLICATIONS: 'FETCHED_PUBLICATIONS',
  FETCHING_PUBLICATIONS: 'FETCHING_PUBLICATIONS',

  SET_QUERY: 'SET_QUERY',

  FETCH_ERROR: 'FETCH_ERROR',
  CLEAR_ERROR: 'CLEAR_ERROR',
};
